name: My First Workflow

on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Step 1"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: List files
        run: ls -la
